name: ms_ess_potal
description: "A new Flutter project."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  google_fonts: ^6.2.1
  syncfusion_flutter_calendar: ^28.1.37
  animated_notch_bottom_bar: ^1.0.3
  permission_handler: ^10.0.0
  path_provider: ^2.0.7
  pdf: ^3.6.0
  dio:

 # ------- Pie chart ------------
  pie_chart: ^5.4.0

 #------ Api ---------------
  http: ^1.2.2
  fluttertoast: ^8.2.10
  flutter_calendar_carousel: ^2.4.4
  font_awesome_flutter: ^10.7.0
#  flutter_html: ^2.1.1
  flutter_widget_from_html: ^0.15.0
#  flutter_widget_from_html: ^0.15.2

  get_storage: ^2.1.1
  shimmer: ^3.0.0
  connectivity_plus: ^6.1.0
  flutter_web_browser: ^0.17.1

#  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/logo/

  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package


